# Generated by Django 3.1.2 on 2020-11-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='List',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Accessory', 'Accessory'), ('Food', 'Food')], max_length=200, null=True),
        ),
    ]
