# Generated by Django 3.1.2 on 2020-11-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_auto_20201130_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='list',
            name='clothes',
        ),
        migrations.RemoveField(
            model_name='list',
            name='food',
        ),
        migrations.AddField(
            model_name='list',
            name='page',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Accessory', 'Accessory'), ('Food', 'Food')], max_length=200, null=True),
        ),
    ]
