# Generated by Django 3.1.2 on 2020-12-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0009_auto_20201206_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='page',
        ),
    ]
