# Generated by Django 3.1.2 on 2020-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0014_auto_20201215_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
