# Generated by Django 3.1.2 on 2020-12-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0016_auto_20201217_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='item_id',
            new_name='page_id',
        ),
    ]
