# Generated by Django 3.1.2 on 2020-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0018_remove_page_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
