# Generated by Django 3.1.2 on 2020-12-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0019_page_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=models.CharField(choices=[('Clothes', 'Clothes'), ('Accessory', 'Accessory'), ('Food', 'Food')], max_length=200, null=True)),
        ),
    ]
