# Generated by Django 3.1.2 on 2020-12-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0020_auto_20201217_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
