# Generated by Django 3.1.2 on 2020-12-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0021_auto_20201217_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_id',
        ),
    ]
