# Generated by Django 3.1.2 on 2020-12-17 13:10

from django.db import migrations, models
import onlineshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0022_remove_page_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='product',
            field=models.CharField(max_length=200, null=True, verbose_name=onlineshop.models.Product),
        ),
    ]
