# Generated by Django 3.1.2 on 2020-12-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0023_auto_20201217_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='product',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
