# Generated by Django 3.1.2 on 2020-12-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0024_auto_20201217_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineshop.product'),
        ),
    ]
