# Generated by Django 3.1.2 on 2020-12-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0025_auto_20201217_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page',
            new_name='page_list',
        ),
    ]
