# Generated by Django 3.1.2 on 2020-12-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0026_auto_20201217_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_list',
            new_name='name',
        ),
    ]
