# Generated by Django 3.1.2 on 2020-12-18 14:02

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0027_auto_20201217_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='page',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
