# Generated by Django 3.1.2 on 2020-12-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0028_auto_20201218_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
