# Generated by Django 3.1.2 on 2020-12-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0030_shippingaddress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
