# Generated by Django 3.1.2 on 2020-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0031_auto_20201219_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
