# Generated by Django 3.1.2 on 2020-12-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0032_auto_20201219_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
