# Generated by Django 3.1.2 on 2020-12-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0036_auto_20201219_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
    ]
